### ISSUE TITLE
distinguishing results per field size

### ISSUE THREAD

**Issue by josephjohnston** [recmo/pc-bench#1]
Hi, thanks for this! Interpreting the results by the graphs on your blog post, it seems you're measuring throughput in field elements per second, without distinguishing the field sizes. 
With the same field element count in input, MSM algos are processing at least 4 times the data of the FRI algos, and it seems that should be reflected in the results.
Am I misunderstanding, or do you have a certain reason in mind?

**Comment by recmo** [comment]
You are correct. I could have picked a different metric like amount of information committed in bits (i.e. $\log_2 |\mathbb{F}|$). MSM algo's would look about 4x better.

The reason I'm not doing this is that unless you can use native field math, you can't really use all those bits. The only use case I can think of that is heavy on native field math is Merkle proofs using a zk-friendly hash function like Poseidon. An important use-case, but imho not representative of general purpose computation, which is what I'm after here.

**Comment by josephjohnston** [comment]
Ah ok, I naively assumed most arithmetization was done using full field elements. 
Like the zk-hash use case you have in mind, what I have in mind is recursion, where $\lambda$ bits are needed. So with $\lambda=128$, FRI commits from 64 bit fields would take twice the time listed, while DLP commits from 256 bit fields would take the time listed but with half their bits wasted. Anyway, thanks for sharing your reasoning.
